Exclude traverson-test-server from browserify bundle
It would be included in the browserified tests because localhost.js and
maze.js require traverson-test-server to start the server on demand when
they run on NodeJS. This never happens when these tests are browserified
and run in the browser.

Also, this solves a mysterious "SyntaxError: Parse error" in mocha_phantomjs:all

Running "mocha_phantomjs:all" (mocha_phantomjs) task
SyntaxError: Parse error

(probably caused by iconv-lite, a indirect dep of traverson-test-server,
with lots of weird characters in its sources)